### ISSUE TITLE
Auto miner does not move forward

### ISSUE THREAD

**Issue by s4sutler100** [mooziii/automated-cobble-miner#1]
Auto miner does not move forward

**Comment by mooziii** [comment]
Yea that's not what i made the mod for. But I think a feature like this may be nice to have

**Comment by s4sutler100** [comment]
I usually mine  two blocks forward 2 blocks down.

**Comment by s4sutler100** [comment]
Having an issue where i press delete and it stops mining.

**Comment by s4sutler100** [comment]
Maybe have a tutorial to record players play style when mining, then  when press delete.
It repeats it?
but stops 2 block in front when tools are broke, full inv, or lava.  ?

**Comment by mooziii** [comment]
I think this would be way complicated as this mod is simply designed for cobblestone generators. You may take a look at [baritone](https://github.com/cabaletta/baritone) for automated farming etc.
